version: '2'
services:
        # The web proxy server
        nginx:
                image: nginx:latest
                ports:
                        - "80:80" # open port 80 for HTTP requests
                volumes:
                        - ./.:/code
                        - ./nginx.conf:/etc/nginx/nginx.conf # copy the nginx configuration to the container
                links:
                        - amt-api # this needs the api to be running
        # Start the standard MongoDB container
        mongodb:
                container_name: "mongodb"
                image: mongo:latest # pull the current mongodb image
                environment:
                        - MONGO_DATA_DIR=/data/db # setup the location of the data
                        - MONGO_LOG_DIR=/dev/log
                # persist the data on the host rather than in the container
                # this makes the container disposable without losing the data
                volumes:
                        - ./data:/data/db
                # forward the standard mongoDB port
                ports:
                        - "27017:27017"
                # start mongodb
                command: mongod --smallfiles
        # The AMT API
        amt-api:
                container_name: "amt-api"
                image: acemonstertoys/amt-api:0.0.0 # this will let us version the api in the future, if we want to
                restart: always
                # link the API to the mongoDB container
                links:
                        - mongodb:mongodb
                # we need that container
                depends_on:
                        - mongodb
                # forward the web port to the server's port
                ports:
                        - "8080:8080"
